[workspace]
members = ["app", "stats", "tuner", "meanstats"]

[package]
name = "jixel"
version = "0.2.8"
edition = "2024"
description = "Tiny JPEG XL encoder"
readme = "README.md"
keywords = ["jpegxl", "jxl", "encoder", "image", "compression"]
license = "BSD-3-Clause OR Apache-2.0"
authors = ["Radzivon Bartoshyk"]
documentation = "https://docs.rs/jixel"
categories = ["multimedia::images", "compression", "encoding"]
homepage = "https://github.com/awxkee/jixel"
repository = "https://github.com/awxkee/jixel"
exclude = ["*.jpg", "/assets", "*.png", "*.sh", "/assets/*", "/scripts/*", "/tools/*", "parameters_fit/*", ".github/*"]
rust-version = "1.94.0"

[features]
default = ["avx", "neon", "sse", "wasm"]
avx = []
neon = []
sse = []
wasm = []

[profile.release]
debug = true